In [38]:
import pandas as pd

soviet_space_dogs = {
"dog_name":[
"Tsygan","Dezik","Lisa","Ryzhik","Smelaya","Malyshka","Bolik","ZIB","Otvazhnaya","Albina",
"Kozyavka","Modnitsa","Laika","Lisichka","Chaika","Bars","Belka","Strelka","Damka","Krasavka",
"Pchyolka","Mushka","Chernushka","Zvezdochka","Veterok","Ugolyok","Ryzhaya","Snezhinka","Zhulka","Button",
"Alpha","Beta","Gamma","Delta","Epsilon","Zeta","Eta","Theta","Iota","Kappa",
"Lambda","Mu","Nu","Xi","Omicron","Pi","Rho","Sigma","Tau","Upsilon",
"Phi","Chi","Psi","Omega","Buran","Volna","Zarya","Mirny","Tuman","Meteor",
"Kometa","Salyut","Orion","Vega","Altair","Argo","Vostok","Soyuz","Luna","Mars",
"Neva","Baikal","Amur","Don","Ural","Volga"
],

"mission":[
"R1 Test","R1 Test","R1 Test","R1 Test","R1 Test","R1 Test","R1 Test","R1 Test","R1 Test","R1 Test",
"R1 Test","R1 Test","Sputnik-2","Vostok Test","Vostok Test","Vostok Test","Sputnik-5","Sputnik-5","Vostok Test","Vostok Test",
"Sputnik-6","Sputnik-6","Sputnik-9","Sputnik-10","Cosmos-110","Cosmos-110","R2 Test","R2 Test","R2 Test","R2 Test",
"R5 Test","R5 Test","R5 Test","R5 Test","R5 Test","R5 Test","R5 Test","R5 Test","R5 Test","R5 Test",
"R7 Test","R7 Test","R7 Test","R7 Test","R7 Test","R7 Test","R7 Test","R7 Test","R7 Test","R7 Test",
"R7 Test","R7 Test","R7 Test","R7 Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test",
"Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test",
"Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test","Vostok Test"
],

"year":[
1951,1951,1951,1951,1951,1951,1952,1952,1952,1953,
1953,1954,1957,1960,1960,1960,1960,1960,1960,1960,
1960,1960,1961,1961,1966,1966,1954,1954,1954,1954,
1955,1955,1955,1955,1955,1955,1955,1955,1955,1955,
1957,1957,1957,1957,1957,1957,1957,1957,1957,1957,
1957,1957,1957,1957,1960,1960,1960,1960,1960,1960,
1960,1960,1960,1960,1960,1960,1960,1960,1960,1960,
1960,1960,1960,1960,1960,1960
],

"rocket":[
"R1","R1","R1","R1","R1","R1","R1","R1","R1","R1",
"R1","R1","Sputnik-2","R7","R7","R7","Vostok-K","Vostok-K","R7","R7",
"Vostok","Vostok","Vostok-K","Vostok-K","Voskhod","Voskhod","R2","R2","R2","R2",
"R5","R5","R5","R5","R5","R5","R5","R5","R5","R5",
"R7","R7","R7","R7","R7","R7","R7","R7","R7","R7",
"R7","R7","R7","R7","Vostok","Vostok","Vostok","Vostok","Vostok","Vostok",
"Vostok","Vostok","Vostok","Vostok","Vostok","Vostok","Vostok","Vostok","Vostok","Vostok",
"Vostok","Vostok","Vostok","Vostok","Vostok","Vostok"
],

"outcome":[
"Survived","Survived","Died","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Died","Died","Died","Died","Survived","Survived","Survived","Survived",
"Died","Died","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived","Survived",
"Survived","Survived","Survived","Survived","Survived","Survived"
]
}

df = pd.DataFrame(soviet_space_dogs)
df

   dog_name      mission  year  rocket   outcome
0    Tsygan      R1 Test  1951      R1  Survived
1     Dezik      R1 Test  1951      R1  Survived
2      Lisa      R1 Test  1951      R1      Died
3    Ryzhik      R1 Test  1951      R1  Survived
4   Smelaya      R1 Test  1951      R1  Survived
..      ...          ...   ...     ...       ...
71   Baikal  Vostok Test  1960  Vostok  Survived
72     Amur  Vostok Test  1960  Vostok  Survived
73      Don  Vostok Test  1960  Vostok  Survived
74     Ural  Vostok Test  1960  Vostok  Survived
75    Volga  Vostok Test  1960  Vostok  Survived

[76 rows x 5 columns]

In [39]:
df.head()

  dog_name  mission  year rocket   outcome
0   Tsygan  R1 Test  1951     R1  Survived
1    Dezik  R1 Test  1951     R1  Survived
2     Lisa  R1 Test  1951     R1      Died
3   Ryzhik  R1 Test  1951     R1  Survived
4  Smelaya  R1 Test  1951     R1  Survived

In [40]:
df.tail()

   dog_name      mission  year  rocket   outcome
71   Baikal  Vostok Test  1960  Vostok  Survived
72     Amur  Vostok Test  1960  Vostok  Survived
73      Don  Vostok Test  1960  Vostok  Survived
74     Ural  Vostok Test  1960  Vostok  Survived
75    Volga  Vostok Test  1960  Vostok  Survived

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76 entries, 0 to 75
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   dog_name  76 non-null     object
 1   mission   76 non-null     object
 2   year      76 non-null     int64
 3   rocket    76 non-null     object
 4   outcome   76 non-null     object
dtypes: int64(1), object(4)
memory usage: 3.1+ KB

In [42]:
df.columns

Index(['dog_name', 'mission', 'year', 'rocket', 'outcome'], dtype='object')

In [43]:
import plotly.graph_objects as go

labels = list(pd.concat([df["mission"], df["rocket"], df["outcome"]]).unique())

label_index = {label:i for i,label in enumerate(labels)}

source = []
target = []
value = []

group1 = df.groupby(["mission","rocket"]).size().reset_index(name="count")

for _,row in group1.iterrows():
    source.append(label_index[row["mission"]])
    target.append(label_index[row["rocket"]])
    value.append(row["count"])

group2 = df.groupby(["rocket","outcome"]).size().reset_index(name="count")

for _,row in group2.iterrows():
    source.append(label_index[row["rocket"]])
    target.append(label_index[row["outcome"]])
    value.append(row["count"])

In [44]:
fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        label=labels
    ),
    link=dict(
        source=source,
        target=target,
        value=value
    )
)])
fig.update_layout(title="Soviet Space Dogs Missions Sankey Diagram")
fig.show()